import { useState, type FormEvent } from 'react';

import { ApiError } from '../../api/client';
import type {
  CreateTestBuyRequest,
  SupplierOffer,
  TestBuyRecommendation,
} from '../../api/contracts';
import { formatDate, formatMoney, formatUnitMoney, humanize } from '../../utils/format';
import { FormFieldError } from './FormFieldError';
import { validateTestBuy, type FieldErrors } from './validation';

type PlannerState =
  | { status: 'idle' }
  | { status: 'submitting' }
  | { status: 'success'; recommendation: TestBuyRecommendation }
  | { status: 'error'; message: string; requestId?: string };

function readableEvidence(value: unknown): string {
  if (value === null || value === undefined || value === '') return 'Not available';
  if (typeof value === 'boolean') return value ? 'Yes' : 'No';
  if (typeof value === 'object') return JSON.stringify(value);
  return String(value);
}

export function TestBuyPlanner({
  offers,
  currencyCode,
  onGenerate,
}: {
  offers: SupplierOffer[];
  currencyCode: string;
  onGenerate: (command: CreateTestBuyRequest) => Promise<TestBuyRecommendation>;
}) {
  const [state, setState] = useState<PlannerState>({ status: 'idle' });
  const [errors, setErrors] = useState<FieldErrors>({});
  const eligibleOffers = offers.filter((offer) => offer.currency_code === currencyCode);
  const hasCurrencyMismatch = eligibleOffers.length !== offers.length;
  const result = state.status === 'success' ? state.recommendation : null;
  const blocked = result?.outcome === 'blocked';

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    const command: CreateTestBuyRequest = {
      supplier_offer_id: String(form.get('supplier_offer_id') ?? ''),
      budget_amount: String(form.get('budget_amount') ?? '').trim(),
      budget_currency_code: currencyCode,
    };
    const nextErrors = validateTestBuy(command);
    setErrors(nextErrors);
    setState({ status: 'idle' });
    if (Object.keys(nextErrors).length > 0) return;

    setState({ status: 'submitting' });
    try {
      const recommendation = await onGenerate(command);
      setState({ status: 'success', recommendation });
    } catch (caught: unknown) {
      const failure = caught instanceof Error ? caught : new Error('Unable to generate scenarios.');
      setState({
        status: 'error',
        message: failure.message,
        requestId: failure instanceof ApiError ? failure.requestId : undefined,
      });
    }
  }

  return (
    <section className="panel test-buy-planner" aria-labelledby="test-buy-heading">
      <div className="section-heading">
        <div>
          <p className="data-label">
            {result
              ? `${result.outcome === 'blocked' ? 'Blocked' : 'Recommended'} · advisory only`
              : 'Advisory planning'}
          </p>
          <h2 id="test-buy-heading">
            {blocked ? 'Test-buy scenarios · Blocked' : 'Test-buy scenarios'}
          </h2>
        </div>
        {result && (
          <span className={`evidence-tag evidence-tag--${blocked ? 'partial' : 'recommended'}`}>
            {blocked ? 'Blocked' : 'Recommended'}
          </span>
        )}
      </div>
      <p className="muted">
        Quantities are generated by the backend from stored demand evidence, confidence, supplier
        lead time and your explicit budget. SellerOS cannot place an order.
      </p>
      {hasCurrencyMismatch && (
        <div className="form-message form-message--warning" role="status">
          Offers in another currency are unavailable for test-buy planning. SellerOS does not infer
          or convert FX rates.
        </div>
      )}
      {eligibleOffers.length === 0 ? (
        <div className="inline-empty">
          <strong>A marketplace-currency supplier offer is required</strong>
          <p>
            Record MOQ, unit cost and lead time in {currencyCode} before requesting a test-buy
            recommendation.
          </p>
        </div>
      ) : (
        <form className="scenario-form" onSubmit={submit} noValidate>
          <div className="form-grid">
            <label className="field">
              <span>Supplier offer</span>
              <select
                name="supplier_offer_id"
                required
                defaultValue=""
                aria-invalid={Boolean(errors.supplier_offer_id)}
                aria-describedby={errors.supplier_offer_id ? 'scenario-offer-error' : undefined}
              >
                <option value="" disabled>
                  Select an offer
                </option>
                {eligibleOffers.map((offer) => (
                  <option value={offer.id} key={offer.id}>
                    {offer.supplier.name} ·{' '}
                    {formatUnitMoney({
                      amount: offer.unit_cost,
                      currency_code: offer.currency_code,
                    })}{' '}
                    · MOQ {offer.minimum_order_quantity} · {offer.lead_time_days} days
                  </option>
                ))}
              </select>
              <FormFieldError id="scenario-offer-error" message={errors.supplier_offer_id} />
            </label>
            <label className="field">
              <span>Available test budget</span>
              <input
                name="budget_amount"
                type="number"
                inputMode="decimal"
                min="0"
                step="0.01"
                required
                aria-invalid={Boolean(errors.budget_amount)}
                aria-describedby={errors.budget_amount ? 'scenario-budget-error' : undefined}
              />
              <FormFieldError id="scenario-budget-error" message={errors.budget_amount} />
            </label>
            <div className="field">
              <label htmlFor="test-buy-currency">Marketplace budget currency</label>
              <input id="test-buy-currency" value={currencyCode} readOnly />
              <small>
                Must match the offer and selected marketplace. FX conversion is not supported.
              </small>
              <FormFieldError id="scenario-currency-error" message={errors.currency_code} />
            </div>
          </div>
          <div className="form-actions">
            <button className="button" type="submit" disabled={state.status === 'submitting'}>
              {state.status === 'submitting' ? 'Generating scenarios…' : 'Generate scenarios'}
            </button>
          </div>
        </form>
      )}

      {state.status === 'idle' && eligibleOffers.length > 0 && (
        <div className="inline-empty scenario-empty">
          <strong>No scenario generated</strong>
          <p>Select an offer and budget to compare conservative, expected and aggressive cases.</p>
        </div>
      )}
      {state.status === 'error' && (
        <div className="form-message form-message--error" role="alert">
          {state.message}
          {state.requestId && (
            <span className="support-reference"> Support reference: {state.requestId}</span>
          )}
        </div>
      )}
      {state.status === 'success' && (
        <div className="scenario-results" role="status" aria-live="polite">
          <div className="scenario-grid">
            {state.recommendation.scenarios.map((scenario) => (
              <article className="scenario-card" key={scenario.scenario}>
                <span
                  className={`evidence-tag evidence-tag--${
                    scenario.status === 'recommended' ? 'recommended' : 'partial'
                  }`}
                >
                  {humanize(scenario.status)}
                </span>
                <h3>{humanize(scenario.scenario)}</h3>
                <dl className="detail-list">
                  <div>
                    <dt>Quantity</dt>
                    <dd>{scenario.quantity} units</dd>
                  </div>
                  <div>
                    <dt>Required investment</dt>
                    <dd>
                      {formatMoney({
                        amount: scenario.required_investment,
                        currency_code: state.recommendation.budget_currency_code,
                      })}
                    </dd>
                  </div>
                  <div>
                    <dt>Scenario unit cost</dt>
                    <dd>
                      {scenario.unit_cost === null
                        ? 'Unavailable'
                        : formatUnitMoney({
                            amount: scenario.unit_cost,
                            currency_code: state.recommendation.budget_currency_code,
                          })}
                    </dd>
                  </div>
                  <div>
                    <dt>Expected sell-through</dt>
                    <dd>
                      {scenario.expected_sell_through_days === null
                        ? 'Unavailable'
                        : `${scenario.expected_sell_through_days} days`}
                    </dd>
                  </div>
                  <div>
                    <dt>Policy status</dt>
                    <dd>{humanize(scenario.status)}</dd>
                  </div>
                </dl>
                {scenario.reason_codes.length > 0 && (
                  <ul className="compact-list reason-code-list">
                    {scenario.reason_codes.map((reason) => (
                      <li key={reason}>{humanize(reason)}</li>
                    ))}
                  </ul>
                )}
              </article>
            ))}
          </div>
          <details className="trace-details">
            <summary>Scenario evidence and policy version</summary>
            <dl className="metric-grid">
              <div>
                <dt>Monthly demand evidence</dt>
                <dd>
                  {state.recommendation.evidence.monthly_demand_units !== null &&
                  state.recommendation.evidence.monthly_demand_label === 'estimated' &&
                  state.recommendation.evidence.monthly_demand_source === 'keepa_monthly_sold'
                    ? `${state.recommendation.evidence.monthly_demand_units} units · Estimated from Keepa monthly sold`
                    : 'Missing · no demand estimate is available'}
                </dd>
              </div>
              <div>
                <dt>Data confidence</dt>
                <dd>
                  {state.recommendation.evidence.data_confidence_score !== null &&
                  state.recommendation.evidence.data_confidence_label === 'calculated'
                    ? `${state.recommendation.evidence.data_confidence_score} / 100 · Calculated`
                    : 'Missing · no calculated confidence is available'}
                </dd>
              </div>
              <div>
                <dt>Market observed on</dt>
                <dd>
                  {state.recommendation.evidence.market_observed_on
                    ? formatDate(state.recommendation.evidence.market_observed_on)
                    : 'Observation date unavailable'}
                </dd>
              </div>
              {state.recommendation.evidence.market_snapshot_at && (
                <div>
                  <dt>Evidence processed</dt>
                  <dd>{formatDate(state.recommendation.evidence.market_snapshot_at)}</dd>
                </div>
              )}
              {state.recommendation.evidence.source_snapshot_id && (
                <div>
                  <dt>Source snapshot ID</dt>
                  <dd className="checksum">{state.recommendation.evidence.source_snapshot_id}</dd>
                </div>
              )}
              {state.recommendation.evidence.data_confidence_score_result_id && (
                <div>
                  <dt>Confidence score result ID</dt>
                  <dd className="checksum">
                    {state.recommendation.evidence.data_confidence_score_result_id}
                  </dd>
                </div>
              )}
              {state.recommendation.evidence.data_confidence_formula_version && (
                <div>
                  <dt>Confidence formula version</dt>
                  <dd>{state.recommendation.evidence.data_confidence_formula_version}</dd>
                </div>
              )}
              <div>
                <dt>Seller inputs</dt>
                <dd>User confirmed supplier offer and budget</dd>
              </div>
              {Object.entries(state.recommendation.inputs).map(([name, value]) => (
                <div key={name}>
                  <dt>{humanize(name)}</dt>
                  <dd>{readableEvidence(value)}</dd>
                </div>
              ))}
              <div>
                <dt>Formula version</dt>
                <dd>{state.recommendation.formula_version}</dd>
              </div>
              <div>
                <dt>Configuration checksum</dt>
                <dd className="checksum">{state.recommendation.configuration_checksum}</dd>
              </div>
            </dl>
          </details>
          {state.recommendation.notices.map((notice) => (
            <div className="form-message form-message--warning" key={notice.code}>
              {notice.message}
            </div>
          ))}
          <p className="decision-disclaimer">
            Advisory recommendation only. Review the evidence before contacting a supplier or
            committing cash.
          </p>
        </div>
      )}
    </section>
  );
}
