"""initial canonical domain

Revision ID: 0001_initial_domain
Revises:
Create Date: 2026-07-19 10:55:58.699772
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001_initial_domain"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organisations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "forecast_scenarios",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organisation_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("assumptions", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_forecast_scenarios_organisation_id"),
        "forecast_scenarios",
        ["organisation_id"],
        unique=False,
    )
    op.create_table(
        "marketplaces",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organisation_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("default_currency_code", sa.String(length=3), nullable=False),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organisation_id", "code", name="uq_marketplace_org_code"),
    )
    op.create_index(
        op.f("ix_marketplaces_organisation_id"), "marketplaces", ["organisation_id"], unique=False
    )
    op.create_table(
        "suppliers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organisation_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organisation_id", "name", name="uq_supplier_org_name"),
    )
    op.create_index(
        op.f("ix_suppliers_organisation_id"), "suppliers", ["organisation_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organisation_id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organisation_id", "email", name="uq_user_org_email"),
    )
    op.create_index(op.f("ix_users_organisation_id"), "users", ["organisation_id"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organisation_id", sa.String(length=36), nullable=False),
        sa.Column("actor_user_id", sa.String(length=36), nullable=True),
        sa.Column("event_type", sa.String(length=120), nullable=False),
        sa.Column("entity_type", sa.String(length=120), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("event_payload", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_events_actor_user_id"), "audit_events", ["actor_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_organisation_id"), "audit_events", ["organisation_id"], unique=False
    )
    op.create_table(
        "import_batches",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organisation_id", sa.String(length=36), nullable=False),
        sa.Column("marketplace_id", sa.String(length=36), nullable=False),
        sa.Column("original_filename", sa.String(length=512), nullable=False),
        sa.Column("checksum", sa.String(length=128), nullable=False),
        sa.Column(
            "status", sa.Enum("pending", "completed", "failed", name="importstatus"), nullable=False
        ),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["marketplace_id"],
            ["marketplaces.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organisation_id", "checksum", name="uq_import_org_checksum"),
    )
    op.create_index(
        op.f("ix_import_batches_marketplace_id"), "import_batches", ["marketplace_id"], unique=False
    )
    op.create_index(
        op.f("ix_import_batches_organisation_id"),
        "import_batches",
        ["organisation_id"],
        unique=False,
    )
    op.create_table(
        "products",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organisation_id", sa.String(length=36), nullable=False),
        sa.Column("marketplace_id", sa.String(length=36), nullable=False),
        sa.Column("asin", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=1000), nullable=True),
        sa.Column("brand", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["marketplace_id"],
            ["marketplaces.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organisation_id", "marketplace_id", "asin", name="uq_product_org_marketplace_asin"
        ),
    )
    op.create_index(
        op.f("ix_products_marketplace_id"), "products", ["marketplace_id"], unique=False
    )
    op.create_index(
        "ix_products_org_marketplace",
        "products",
        ["organisation_id", "marketplace_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_products_organisation_id"), "products", ["organisation_id"], unique=False
    )
    op.create_table(
        "cost_profiles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organisation_id", sa.String(length=36), nullable=False),
        sa.Column("product_id", sa.String(length=36), nullable=True),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("supplier_unit_cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("freight_cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("prep_packaging_cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cost_profiles_organisation_id"), "cost_profiles", ["organisation_id"], unique=False
    )
    op.create_index(
        op.f("ix_cost_profiles_product_id"), "cost_profiles", ["product_id"], unique=False
    )
    op.create_table(
        "import_columns",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("import_batch_id", sa.String(length=36), nullable=False),
        sa.Column("source_header", sa.String(length=512), nullable=False),
        sa.Column("canonical_field", sa.String(length=128), nullable=True),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("is_mapped", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["import_batches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("import_batch_id", "source_header", name="uq_import_column_header"),
    )
    op.create_index(
        op.f("ix_import_columns_import_batch_id"),
        "import_columns",
        ["import_batch_id"],
        unique=False,
    )
    op.create_table(
        "import_row_errors",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("import_batch_id", sa.String(length=36), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("field_name", sa.String(length=128), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["import_batches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_import_row_errors_import_batch_id"),
        "import_row_errors",
        ["import_batch_id"],
        unique=False,
    )
    op.create_table(
        "inventory_positions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organisation_id", sa.String(length=36), nullable=False),
        sa.Column("product_id", sa.String(length=36), nullable=False),
        sa.Column("units_on_hand", sa.Integer(), nullable=False),
        sa.Column("units_reserved", sa.Integer(), nullable=False),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_positions_organisation_id"),
        "inventory_positions",
        ["organisation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_positions_product_id"),
        "inventory_positions",
        ["product_id"],
        unique=False,
    )
    op.create_table(
        "pricing_plans",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("product_id", sa.String(length=36), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("minimum_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("target_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("minimum_price <= target_price", name="ck_pricing_min_lte_target"),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pricing_plans_product_id"), "pricing_plans", ["product_id"], unique=False
    )
    op.create_table(
        "product_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("product_id", sa.String(length=36), nullable=False),
        sa.Column("import_batch_id", sa.String(length=36), nullable=True),
        sa.Column("snapshot_kind", sa.Enum("keepa", "manual", name="snapshotkind"), nullable=False),
        sa.Column("snapshot_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("market_metrics", sa.JSON(), nullable=False),
        sa.Column("source_row_number", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["import_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_product_snapshots_import_batch_id"),
        "product_snapshots",
        ["import_batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_snapshots_product_id"), "product_snapshots", ["product_id"], unique=False
    )
    op.create_index(
        "ix_snapshots_product_taken_at",
        "product_snapshots",
        ["product_id", "snapshot_at"],
        unique=False,
    )
    op.create_table(
        "supplier_offers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("supplier_id", sa.String(length=36), nullable=False),
        sa.Column("product_id", sa.String(length=36), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("minimum_order_quantity", sa.Integer(), nullable=False),
        sa.Column("lead_time_days", sa.Integer(), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_supplier_offers_product_id"), "supplier_offers", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_supplier_offers_supplier_id"), "supplier_offers", ["supplier_id"], unique=False
    )
    op.create_table(
        "raw_attributes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("source_header", sa.String(length=512), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["product_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "snapshot_id", "source_header", name="uq_raw_attribute_snapshot_header"
        ),
    )
    op.create_index(
        op.f("ix_raw_attributes_snapshot_id"), "raw_attributes", ["snapshot_id"], unique=False
    )
    op.create_table(
        "score_results",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("score_name", sa.String(length=120), nullable=False),
        sa.Column("formula_version", sa.String(length=80), nullable=False),
        sa.Column("score_value", sa.Integer(), nullable=False),
        sa.Column("inputs", sa.JSON(), nullable=False),
        sa.Column("reason_codes", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["product_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "snapshot_id", "score_name", "formula_version", name="uq_score_snapshot_name_version"
        ),
    )
    op.create_index(
        op.f("ix_score_results_snapshot_id"), "score_results", ["snapshot_id"], unique=False
    )
    op.create_table(
        "strategy_recommendations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("strategy", sa.String(length=80), nullable=False),
        sa.Column("rules_version", sa.String(length=80), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["product_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_strategy_recommendations_snapshot_id"),
        "strategy_recommendations",
        ["snapshot_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_strategy_recommendations_snapshot_id"), table_name="strategy_recommendations"
    )
    op.drop_table("strategy_recommendations")
    op.drop_index(op.f("ix_score_results_snapshot_id"), table_name="score_results")
    op.drop_table("score_results")
    op.drop_index(op.f("ix_raw_attributes_snapshot_id"), table_name="raw_attributes")
    op.drop_table("raw_attributes")
    op.drop_index(op.f("ix_supplier_offers_supplier_id"), table_name="supplier_offers")
    op.drop_index(op.f("ix_supplier_offers_product_id"), table_name="supplier_offers")
    op.drop_table("supplier_offers")
    op.drop_index("ix_snapshots_product_taken_at", table_name="product_snapshots")
    op.drop_index(op.f("ix_product_snapshots_product_id"), table_name="product_snapshots")
    op.drop_index(op.f("ix_product_snapshots_import_batch_id"), table_name="product_snapshots")
    op.drop_table("product_snapshots")
    op.drop_index(op.f("ix_pricing_plans_product_id"), table_name="pricing_plans")
    op.drop_table("pricing_plans")
    op.drop_index(op.f("ix_inventory_positions_product_id"), table_name="inventory_positions")
    op.drop_index(op.f("ix_inventory_positions_organisation_id"), table_name="inventory_positions")
    op.drop_table("inventory_positions")
    op.drop_index(op.f("ix_import_row_errors_import_batch_id"), table_name="import_row_errors")
    op.drop_table("import_row_errors")
    op.drop_index(op.f("ix_import_columns_import_batch_id"), table_name="import_columns")
    op.drop_table("import_columns")
    op.drop_index(op.f("ix_cost_profiles_product_id"), table_name="cost_profiles")
    op.drop_index(op.f("ix_cost_profiles_organisation_id"), table_name="cost_profiles")
    op.drop_table("cost_profiles")
    op.drop_index(op.f("ix_products_organisation_id"), table_name="products")
    op.drop_index("ix_products_org_marketplace", table_name="products")
    op.drop_index(op.f("ix_products_marketplace_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_import_batches_organisation_id"), table_name="import_batches")
    op.drop_index(op.f("ix_import_batches_marketplace_id"), table_name="import_batches")
    op.drop_table("import_batches")
    op.drop_index(op.f("ix_audit_events_organisation_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_actor_user_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_users_organisation_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_suppliers_organisation_id"), table_name="suppliers")
    op.drop_table("suppliers")
    op.drop_index(op.f("ix_marketplaces_organisation_id"), table_name="marketplaces")
    op.drop_table("marketplaces")
    op.drop_index(op.f("ix_forecast_scenarios_organisation_id"), table_name="forecast_scenarios")
    op.drop_table("forecast_scenarios")
    op.drop_table("organisations")
    # ### end Alembic commands ###
