"""gst india filing workflow

Revision ID: 0005_gst_india
Revises: 0004_dated_keepa_datasets
Create Date: 2026-07-25 16:42:05.692172
"""

from collections.abc import Sequence

import sqlalchemy as sa

import app.db.types
from alembic import op

revision: str = "0005_gst_india"
down_revision: str | None = "0004_dated_keepa_datasets"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gst_registrations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organisation_id", sa.String(length=36), nullable=False),
        sa.Column("marketplace_id", sa.String(length=36), nullable=False),
        sa.Column("gstin", sa.String(length=15), nullable=False),
        sa.Column("legal_name", sa.String(length=255), nullable=False),
        sa.Column("filing_frequency", sa.String(length=16), nullable=False),
        sa.Column("created_at", app.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["marketplace_id"],
            ["marketplaces.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organisation_id", "gstin", name="uq_gst_registration_org_gstin"),
    )
    op.create_index(
        "ix_gst_registration_scope",
        "gst_registrations",
        ["organisation_id", "marketplace_id"],
        unique=False,
    )
    op.create_table(
        "gst_filing_periods",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organisation_id", sa.String(length=36), nullable=False),
        sa.Column("marketplace_id", sa.String(length=36), nullable=False),
        sa.Column("gst_registration_id", sa.String(length=36), nullable=False),
        sa.Column("period_month", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "collecting",
                "validating",
                "needs_attention",
                "draft_ready",
                "approved",
                "exported",
                "user_confirmed_filed",
                name="gstfilingstatus",
            ),
            nullable=False,
        ),
        sa.Column("completeness_confirmed", sa.Boolean(), nullable=False),
        sa.Column("approved_at", app.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("filed_arn", sa.String(length=64), nullable=True),
        sa.Column("filed_at", app.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("created_at", app.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["gst_registration_id"],
            ["gst_registrations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["marketplace_id"],
            ["marketplaces.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("gst_registration_id", "period_month", name="uq_gst_filing_period"),
    )
    op.create_index(
        "ix_gst_filing_scope_period",
        "gst_filing_periods",
        ["organisation_id", "marketplace_id", "period_month"],
        unique=False,
    )
    op.create_table(
        "gst_return_drafts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("filing_period_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("formula_version", sa.String(length=80), nullable=False),
        sa.Column("configuration_checksum", sa.String(length=64), nullable=False),
        sa.Column("sections", sa.JSON(), nullable=False),
        sa.Column("totals", sa.JSON(), nullable=False),
        sa.Column("created_at", app.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["filing_period_id"],
            ["gst_filing_periods.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("filing_period_id", "version", name="uq_gst_draft_period_version"),
    )
    op.create_index(
        op.f("ix_gst_return_drafts_filing_period_id"),
        "gst_return_drafts",
        ["filing_period_id"],
        unique=False,
    )
    op.create_table(
        "gst_source_documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("filing_period_id", sa.String(length=36), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("original_filename", sa.String(length=512), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("staged", "parsed", "rejected", name="gstdocumentstatus"),
            nullable=False,
        ),
        sa.Column("schema_version", sa.String(length=80), nullable=True),
        sa.Column("parsed_payload", sa.JSON(), nullable=False),
        sa.Column("uploaded_at", app.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["filing_period_id"],
            ["gst_filing_periods.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("filing_period_id", "checksum", name="uq_gst_document_period_checksum"),
    )
    op.create_index(
        op.f("ix_gst_source_documents_filing_period_id"),
        "gst_source_documents",
        ["filing_period_id"],
        unique=False,
    )
    op.create_table(
        "gst_validation_exceptions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("filing_period_id", sa.String(length=36), nullable=False),
        sa.Column("source_document_id", sa.String(length=36), nullable=True),
        sa.Column("code", sa.String(length=120), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("status", sa.Enum("open", "resolved", name="gstexceptionstatus"), nullable=False),
        sa.Column("created_at", app.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["filing_period_id"],
            ["gst_filing_periods.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["gst_source_documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_gst_exception_period_status",
        "gst_validation_exceptions",
        ["filing_period_id", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_gst_exception_period_status", table_name="gst_validation_exceptions")
    op.drop_table("gst_validation_exceptions")
    op.drop_index(
        op.f("ix_gst_source_documents_filing_period_id"), table_name="gst_source_documents"
    )
    op.drop_table("gst_source_documents")
    op.drop_index(op.f("ix_gst_return_drafts_filing_period_id"), table_name="gst_return_drafts")
    op.drop_table("gst_return_drafts")
    op.drop_index("ix_gst_filing_scope_period", table_name="gst_filing_periods")
    op.drop_table("gst_filing_periods")
    op.drop_index("ix_gst_registration_scope", table_name="gst_registrations")
    op.drop_table("gst_registrations")
    # ### end Alembic commands ###
